// Generated by gencpp from file wk3_pkg/signal_msg.msg
// DO NOT EDIT!


#ifndef WK3_PKG_MESSAGE_SIGNAL_MSG_H
#define WK3_PKG_MESSAGE_SIGNAL_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wk3_pkg
{
template <class ContainerAllocator>
struct signal_msg_
{
  typedef signal_msg_<ContainerAllocator> Type;

  signal_msg_()
    : output_val(0.0)  {
    }
  signal_msg_(const ContainerAllocator& _alloc)
    : output_val(0.0)  {
  (void)_alloc;
    }



   typedef float _output_val_type;
  _output_val_type output_val;





  typedef boost::shared_ptr< ::wk3_pkg::signal_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wk3_pkg::signal_msg_<ContainerAllocator> const> ConstPtr;

}; // struct signal_msg_

typedef ::wk3_pkg::signal_msg_<std::allocator<void> > signal_msg;

typedef boost::shared_ptr< ::wk3_pkg::signal_msg > signal_msgPtr;
typedef boost::shared_ptr< ::wk3_pkg::signal_msg const> signal_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wk3_pkg::signal_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wk3_pkg::signal_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wk3_pkg::signal_msg_<ContainerAllocator1> & lhs, const ::wk3_pkg::signal_msg_<ContainerAllocator2> & rhs)
{
  return lhs.output_val == rhs.output_val;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wk3_pkg::signal_msg_<ContainerAllocator1> & lhs, const ::wk3_pkg::signal_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wk3_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::wk3_pkg::signal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wk3_pkg::signal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wk3_pkg::signal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wk3_pkg::signal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wk3_pkg::signal_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wk3_pkg::signal_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wk3_pkg::signal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4765125923055d13d8bbf99b4bfa51a";
  }

  static const char* value(const ::wk3_pkg::signal_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4765125923055d1ULL;
  static const uint64_t static_value2 = 0x3d8bbf99b4bfa51aULL;
};

template<class ContainerAllocator>
struct DataType< ::wk3_pkg::signal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wk3_pkg/signal_msg";
  }

  static const char* value(const ::wk3_pkg::signal_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wk3_pkg::signal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 output_val\n"
;
  }

  static const char* value(const ::wk3_pkg::signal_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wk3_pkg::signal_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signal_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wk3_pkg::signal_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wk3_pkg::signal_msg_<ContainerAllocator>& v)
  {
    s << indent << "output_val: ";
    Printer<float>::stream(s, indent + "  ", v.output_val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WK3_PKG_MESSAGE_SIGNAL_MSG_H
